name: piima
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2


  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.3
  flutter_launcher_icons: ^0.9.2
  flutter_iconly: ^1.0.2
  fluttericon: ^2.0.0
  pie_chart: ^5.1.0
  font_awesome_flutter: ^9.2.0
  flutter_scroll_to_top: ^2.1.1
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  like_button: ^2.0.4
  flutter_animated_button: ^2.0.0
  fullscreen: ^1.0.3
  url_launcher: ^6.0.20
  fl_chart: ^0.46.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - images/
   - rasm/

  fonts:
    - family: Josefino-Sans
      fonts:
        - asset: fonts/JosefinSans-MediumItalic.ttf